# Generated by Django 5.1.1 on 2024-11-19 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('turma', models.CharField(max_length=100, verbose_name='Turma')),
                ('semestre', models.CharField(max_length=100, verbose_name='Semestre')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('eventos_extraordinarios', models.CharField(blank=True, max_length=255, null=True, verbose_name='Eventos Extraordinários')),
                ('conteudo_programatico', models.TextField(verbose_name='Conteúdo Programático')),
                ('metodologia', models.TextField(verbose_name='Metodologia')),
                ('recursos_necessarios', models.TextField(verbose_name='Recursos Necessários')),
                ('avaliacao_observacoes', models.TextField(blank=True, null=True, verbose_name='Avaliação e Observações')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['data_aula'],
            },
        ),
        migrations.CreateModel(
            name='Caderneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField(verbose_name='Data da Aula')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('eventos', models.TextField(blank=True, null=True, verbose_name='Eventos')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('materiais', models.TextField(blank=True, null=True, verbose_name='Materiais')),
                ('atividade', models.TextField(blank=True, null=True, verbose_name='Atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Caderneta',
                'verbose_name_plural': 'Cadernetas',
                'ordering': ['data_aula'],
            },
        ),
    ]
