# Generated by Django 5.1.1 on 2024-11-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanLab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanLab.disciplina'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanLab.semestre'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlanLab.turma'),
        ),
    ]
