# Generated by Django 5.1.1 on 2024-10-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanLab', '0002_alter_aula_avaliacao_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
