# Generated by Django 5.1.1 on 2024-10-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanLab', '0003_alter_aula_semestre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='aula',
            name='eventos_extraordinarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
