# Generated by Django 5.1.1 on 2024-10-11 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanLab', '0004_delete_usuario_alter_aula_eventos_extraordinarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['data_aula'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterField(
            model_name='aula',
            name='avaliacao_observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Avaliação e Observações'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='conteudo_programatico',
            field=models.TextField(verbose_name='Conteúdo Programático'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='data_aula',
            field=models.DateField(verbose_name='Data da Aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.CharField(max_length=100, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='eventos_extraordinarios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eventos Extraordinários'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='metodologia',
            field=models.TextField(verbose_name='Metodologia'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='recursos_necessarios',
            field=models.TextField(verbose_name='Recursos Necessários'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='semestre',
            field=models.IntegerField(verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turma',
            field=models.CharField(max_length=100, verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
